# Generated by Django 5.2.15 on 2026-07-01 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_payment", "Awaiting Payment"),
                            ("confirmed", "Confirmed"),
                            ("preparing", "Preparing"),
                            ("ready", "Ready for Pickup"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="awaiting_payment",
                        max_length=20,
                    ),
                ),
                (
                    "fulfillment_type",
                    models.CharField(
                        choices=[("pickup", "Pickup")], default="pickup", max_length=20
                    ),
                ),
                ("pickup_date", models.DateField()),
                ("pickup_window_start", models.TimeField(blank=True, null=True)),
                ("pickup_window_end", models.TimeField(blank=True, null=True)),
                ("order_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "advance_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Advance due in-app = order_total × (advance_percentage / 100).",
                        max_digits=10,
                    ),
                ),
                (
                    "balance_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Remaining balance collected offline = order_total − advance_amount.",
                        max_digits=10,
                    ),
                ),
                ("balance_paid_at", models.DateTimeField(blank=True, null=True)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "balance_paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="balance_payments_marked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                (
                    "unit_price_snapshot",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit/lb/size at time of order.",
                        max_digits=10,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cake_size", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "cake_flavor_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cake_inscription", models.TextField(blank=True)),
                ("cake_special_requests", models.TextField(blank=True)),
                (
                    "catering_option_label",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "catering_serves_note",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "catering_variant_choice",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("catering_special_requests", models.TextField(blank=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gateway", models.CharField(default="stripe", max_length=50)),
                (
                    "gateway_reference",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("captured", "Captured"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
