# Generated by Django 5.2.15 on 2026-07-01 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_category_tax_rate"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default="0.00",
                help_text="Total tax snapshotted at order placement (sum of per-line tax).",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
