# Generated by Django 5.2.15 on 2026-07-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderitem_custom_options_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="custom_options_snapshot",
            field=models.TextField(blank=True),
        ),
    ]
