# Generated by Django 5.2.15 on 2026-07-01 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cake", "Cake"),
                            ("meat", "Meat"),
                            ("grocery", "Grocery"),
                            ("catering", "Catering"),
                        ],
                        max_length=20,
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                (
                    "unit_price_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("cake_size", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "cake_flavor_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cake_inscription", models.TextField(blank=True)),
                ("cake_special_requests", models.TextField(blank=True)),
                (
                    "catering_option_label",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "catering_serves_note",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("catering_pricing_mode", models.CharField(blank=True, max_length=20)),
                (
                    "catering_variant_choice",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("catering_special_requests", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
