# Generated by Django 5.2.15 on 2026-07-01 01:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="Our Store", max_length=200)),
                (
                    "advance_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        help_text="Percentage of the order total charged as the advance payment (0–100).",
                        max_digits=5,
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="State meal tax rate as a decimal (e.g. 0.0625 for 6.25%). Reserved for Phase 3 — not yet applied to order totals.",
                        max_digits=6,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configuration",
            },
        ),
        migrations.CreateModel(
            name="StoreClosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "special_open_time",
                    models.TimeField(
                        blank=True,
                        help_text="Set for a partial-day override; leave blank for a full closure.",
                        null=True,
                    ),
                ),
                (
                    "special_close_time",
                    models.TimeField(
                        blank=True,
                        help_text="Set for a partial-day override; leave blank for a full closure.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Closure / Special Hours",
                "verbose_name_plural": "Store Closures / Special Hours",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="StoreHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        unique=True,
                    ),
                ),
                (
                    "open_time",
                    models.TimeField(
                        blank=True,
                        help_text="Leave blank when is_closed is checked.",
                        null=True,
                    ),
                ),
                (
                    "close_time",
                    models.TimeField(
                        blank=True,
                        help_text="Leave blank when is_closed is checked.",
                        null=True,
                    ),
                ),
                ("is_closed", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Store Hours",
                "verbose_name_plural": "Store Hours",
                "ordering": ["weekday"],
            },
        ),
    ]
