# Generated by Django 5.2.15 on 2026-07-01 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="tax_rate",
        ),
    ]
