# Generated by Django 5.2.15 on 2026-07-01 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CakeFlavor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide this product on the storefront without deleting it.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cake", "Cake"),
                            ("meat", "Meat"),
                            ("grocery", "Grocery"),
                            ("catering", "Catering"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CateringSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Catering Section",
                "verbose_name_plural": "Catering Sections",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CakeProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cake Product",
                "verbose_name_plural": "Cake Products",
            },
            bases=("catalog.product",),
        ),
        migrations.CreateModel(
            name="CateringProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="catalog.product",
                    ),
                ),
                (
                    "inquiry_only",
                    models.BooleanField(
                        default=False,
                        help_text="Show without a price; not directly orderable.",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.cateringsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catering Product",
                "verbose_name_plural": "Catering Products",
            },
            bases=("catalog.product",),
        ),
        migrations.CreateModel(
            name="GroceryProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="catalog.product",
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                "verbose_name": "Grocery Product",
                "verbose_name_plural": "Grocery Products",
            },
            bases=("catalog.product",),
        ),
        migrations.CreateModel(
            name="MeatProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="catalog.product",
                    ),
                ),
                (
                    "price_per_lb",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in USD per pound.",
                        max_digits=8,
                    ),
                ),
            ],
            options={
                "verbose_name": "Meat Product",
                "verbose_name_plural": "Meat Products",
            },
            bases=("catalog.product",),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.category",
            ),
        ),
        migrations.CreateModel(
            name="CakeSizePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("6_inch", "6 Inch"),
                            ("8_inch", "8 Inch"),
                            ("9_inch", "9 Inch"),
                            ("10_inch", "10 Inch"),
                            ("slice", "Individual Slice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "cake_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="size_prices",
                        to="catalog.cakeproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["size"],
                "unique_together": {("cake_product", "size")},
            },
        ),
        migrations.CreateModel(
            name="CateringVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='e.g. "Meat", "Veggie", "Chicken"', max_length=100
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "catering_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.cateringproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "label"],
                "unique_together": {("catering_product", "label")},
            },
        ),
        migrations.CreateModel(
            name="CateringOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='e.g. "Regular", "Half Tray", "Per Pound"',
                        max_length=100,
                    ),
                ),
                (
                    "serves_note",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Serves 18 to 20", "24 to 48 pcs"',
                        max_length=200,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "pricing_mode",
                    models.CharField(
                        choices=[
                            (
                                "by_tray",
                                "By Tray / Unit (fixed price × integer quantity)",
                            ),
                            (
                                "by_weight",
                                "By Weight per lb (price × customer-entered weight)",
                            ),
                        ],
                        default="by_tray",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "catering_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="catalog.cateringproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "label"],
                "unique_together": {("catering_product", "label")},
            },
        ),
    ]
