# Generated by Django 5.2.15 on 2026-07-01 03:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="Tax rate as a decimal (e.g. 0.0625 for 6.25%). Applied per line at checkout.",
                max_digits=6,
            ),
        ),
    ]
